name: Eksperimen SML

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.1
      uses: actions/setup-python@v4
      with: 
        python-version: "3.12.1"
        
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
        
    - name: Running Preprocessing
      run: python preprocessing/automate_DzulFikri.py
      
    - name: Commit & Push into
      run: | 
        git config --global user.name "${{ secrets.USERNAME_GIT }}"
        git config --global user.email "${{ secrets.EMAIL_GIT }}"
        git add preprocessing/
        git commit -m "UPDATE data"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      
